# MLProject/conda.yaml
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip<=25.3
  - pip:
      - mlflow==2.18.0
      - cloudpickle==3.1.2
      - numpy==1.26.4
      - psutil==5.9.8
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - pandas
      - optuna
      - matplotlib
      - seaborn
name: mlflow-env
